/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class BloodBanks extends javax.swing.JFrame {

    /**
     * Creates new form BloodBanks
     */
    public BloodBanks() {
        initComponents();
        BloodBankTable();
    }
    
    public void BloodBankTable(){
               Connector con=new Connector();
               con.createConnection();
               
        try{
            DefaultTableModel model; 
            model =(DefaultTableModel) BloodBankTable.getModel();
            Statement stmt=Connector.conn.createStatement();
            String sql="select bloodbank.BBno,bloodbank.BBName,bloodbank.PhoneNo,bloodbankmanager.Name,bloodbankmanager.PhoneNumber from bloodbank inner join bloodbankmanager on bloodbank.BBNo=bloodbankmanager.BBNo;";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                String bbno=rs.getString("BBNo");
                String bbname=rs.getString("BBName");
                String phoneno=rs.getString("PhoneNo");
                String manager=rs.getString("Name");
                String phone=rs.getString("PhoneNumber");
                model.addRow(new Object[] {bbno,bbname,phoneno,manager,phone});
            }
            rs.close();
            stmt.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BloodBankTable = new javax.swing.JTable();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BloodBankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Blood Bank Number", "Blood Bank Name", "Phone Number", "Blood Bank Manager", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BloodBankTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(BloodBankTable);
        if (BloodBankTable.getColumnModel().getColumnCount() > 0) {
            BloodBankTable.getColumnModel().getColumn(0).setResizable(false);
            BloodBankTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            BloodBankTable.getColumnModel().getColumn(1).setResizable(false);
            BloodBankTable.getColumnModel().getColumn(1).setPreferredWidth(450);
            BloodBankTable.getColumnModel().getColumn(2).setResizable(false);
            BloodBankTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            BloodBankTable.getColumnModel().getColumn(3).setResizable(false);
            BloodBankTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            BloodBankTable.getColumnModel().getColumn(4).setResizable(false);
            BloodBankTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(695, 1008, Short.MAX_VALUE)
                .addComponent(CloseButton)
                .addGap(27, 27, 27))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(CloseButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
       this.dispose();
       Welcome w=new Welcome();
       w.Welcome();
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void BloodBank() {
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodBanks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BloodBankTable;
    private javax.swing.JButton CloseButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
