/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import static bloodbank.Connector.conn;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.Integer;
import java.time.LocalDate;
import java.time.Period;

/**
 *
 * @author hp
 */
public class DonorRegistration extends javax.swing.JFrame {

    /**
     * Creates new form DonorRegistration
     */
    public DonorRegistration() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        DonorName = new javax.swing.JTextField();
        Sex = new javax.swing.JLabel();
        DonorAge = new javax.swing.JTextField();
        EmailId = new javax.swing.JLabel();
        DonorEmailId = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        DonorPhoneNumber = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DonorAddress = new javax.swing.JTextArea();
        BloodType = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        Blood = new javax.swing.JComboBox<>();
        DonorSex = new javax.swing.JComboBox<>();
        DonorIdButton = new javax.swing.JButton();
        DonorIdText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AgeButton = new javax.swing.JButton();
        DD = new javax.swing.JTextField();
        MM = new javax.swing.JTextField();
        YYYY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ViewDonors = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        DonorsTable = new javax.swing.JTable();
        CloseButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Blood1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IdText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        UpdateCombo = new javax.swing.JComboBox<>();
        Update = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        UpdateText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DeleteDonorText = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        DeleteTable = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("DONOR REGISTRATION");

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name");

        Sex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sex.setText("Sex");

        DonorAge.setEditable(false);

        EmailId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailId.setText("Email ID");

        PhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhoneNumber.setText("Phone Number");

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address.setText("Address");

        DonorAddress.setColumns(20);
        DonorAddress.setRows(5);
        jScrollPane2.setViewportView(DonorAddress);

        BloodType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BloodType.setText("Blood Type");

        ClearButton.setBackground(new java.awt.Color(0, 153, 153));
        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(153, 0, 153));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(0, 153, 153));
        SubmitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(153, 0, 153));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        Blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        DonorSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        DonorIdButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DonorIdButton.setText("DonorId");
        DonorIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorIdButtonActionPerformed(evt);
            }
        });

        DonorIdText.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date Of Birth");

        AgeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgeButton.setText("Age");
        AgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("/");

        jLabel5.setText("DD           /        MM       /              YYYY");

        DOB.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Entered Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BloodType)
                    .addComponent(Name)
                    .addComponent(Sex)
                    .addComponent(PhoneNumber)
                    .addComponent(Address)
                    .addComponent(DonorIdButton)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(AgeButton)
                    .addComponent(EmailId))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorIdText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorEmailId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorName)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(ClearButton)
                        .addGap(79, 79, 79)
                        .addComponent(SubmitButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DonorIdButton)
                    .addComponent(DonorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(DonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex)
                    .addComponent(DonorSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeButton)
                    .addComponent(DonorAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailId)
                    .addComponent(DonorEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneNumber)
                    .addComponent(DonorPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BloodType)
                    .addComponent(Blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(SubmitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        ViewDonors.setBackground(new java.awt.Color(255, 51, 51));
        ViewDonors.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewDonors.setForeground(new java.awt.Color(255, 255, 255));
        ViewDonors.setText("VIEW ALL DONORS");
        ViewDonors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDonorsActionPerformed(evt);
            }
        });

        DonorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DonorId", "Name", "Sex", "DOB", "Age", "EmailID", "Phone Number", "Address", "Blood Group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DonorsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(DonorsTable);
        if (DonorsTable.getColumnModel().getColumnCount() > 0) {
            DonorsTable.getColumnModel().getColumn(0).setResizable(false);
            DonorsTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            DonorsTable.getColumnModel().getColumn(1).setResizable(false);
            DonorsTable.getColumnModel().getColumn(2).setResizable(false);
            DonorsTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            DonorsTable.getColumnModel().getColumn(3).setResizable(false);
            DonorsTable.getColumnModel().getColumn(4).setResizable(false);
            DonorsTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            DonorsTable.getColumnModel().getColumn(5).setResizable(false);
            DonorsTable.getColumnModel().getColumn(6).setResizable(false);
            DonorsTable.getColumnModel().getColumn(7).setResizable(false);
            DonorsTable.getColumnModel().getColumn(8).setResizable(false);
            DonorsTable.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        CloseButton.setBackground(new java.awt.Color(255, 255, 255));
        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 0, 0));
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Select Blood Group to view donors");

        Blood1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VIEW DONORS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ViewDonors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Blood1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewDonors)
                    .addComponent(CloseButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Blood1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Update Information");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Enter the Donor ID to update information");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Choose the field to be updated");

        UpdateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DonorName", "Sex", "DOB", "Age", "EmailId", "PhoneNo", "Address", "BloodType" }));

        Update.setBackground(new java.awt.Color(255, 0, 51));
        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Enter the new value to be updated");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdText)
                            .addComponent(UpdateCombo, 0, 109, Short.MAX_VALUE)
                            .addComponent(UpdateText))
                        .addGap(79, 79, 79)
                        .addComponent(Update)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(UpdateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Update)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UpdateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Delete Donors");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Enter the Donor ID to delete records");

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        DeleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor ID", "Name", "Blood Type", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DeleteTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(DeleteTable);
        if (DeleteTable.getColumnModel().getColumnCount() > 0) {
            DeleteTable.getColumnModel().getColumn(0).setResizable(false);
            DeleteTable.getColumnModel().getColumn(1).setResizable(false);
            DeleteTable.getColumnModel().getColumn(2).setResizable(false);
            DeleteTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(DeleteButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(DeleteDonorText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteDonorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        Connector con=new Connector();
        con.createConnection();
       
        try {
            Statement stmt=conn.createStatement();
            PreparedStatement pst,p;
            String sql="Insert into donor(DonorId,DonorName,Sex,DOB,Age,EmailId,PhoneNo,Address,BloodType) values(?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            
        pst.setString(1,DonorIdText.getText());   
        pst.setString(2,DonorName.getText());
        pst.setString(3,DonorSex.getSelectedItem().toString());
        pst.setString(4,DOB.getText());
        pst.setString(5,DonorAge.getText());
        pst.setString(6,DonorEmailId.getText());
        pst.setString(7,DonorPhoneNumber.getText());
        pst.setString(8,DonorAddress.getText());
        pst.setString(9,Blood.getSelectedItem().toString());
        pst.execute();
        
        String sql1="update blood set quantity=quantity+1 where BloodType=?";
        p=conn.prepareStatement(sql1);
        p.setString(1,Blood.getSelectedItem().toString());
        p.execute();
            JOptionPane.showMessageDialog(null,"Details inserted");  
            
        DonorIdText.setText("");
        DonorName.setText("");
        DD.setText("");
        MM.setText("");
        YYYY.setText("");
        DOB.setText("");
        DonorAge.setText("");
        DonorEmailId.setText("");
        DonorPhoneNumber.setText("");
        DonorAddress.setText("");   
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Invalid information");
        } 
       
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        DonorIdText.setText("");
        DonorName.setText("");
        DD.setText("");
        MM.setText("");
        YYYY.setText("");
        DOB.setText("");
        DonorAge.setText("");
        DonorEmailId.setText("");
        DonorPhoneNumber.setText("");
        DonorAddress.setText("");        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.dispose();
        Welcome w=new Welcome();
        w.Welcome();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void DonorIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorIdButtonActionPerformed
        try{                                         
        Connector con=new Connector();
        con.createConnection();
        Statement stmt=Connector.conn.createStatement();
        String sql="select DonorId+1 from donor where DonorId=(select max(DonorId) from donor);";
        ResultSet rs=stmt.executeQuery(sql);
        while(rs.next())
        {
        DonorIdText.setText(rs.getString("DonorId+1"));
        }
    } 
    catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_DonorIdButtonActionPerformed

    private void AgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeButtonActionPerformed
        int day=Integer.parseInt(DD.getText());
        int month=Integer.parseInt(MM.getText());
        int years=Integer.parseInt(YYYY.getText());
        
        LocalDate birthday=LocalDate.of(years,month,day);
        LocalDate nowDate=LocalDate.now();
        int period = Period.between(birthday, nowDate).getYears();
        DOB.setText(String.valueOf(LocalDate.of(years,month,day)));
        DonorAge.setText(String.valueOf(period));
    }//GEN-LAST:event_AgeButtonActionPerformed

    private void ViewDonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDonorsActionPerformed
              Connector con=new Connector();
               con.createConnection();
               
        try{
            DefaultTableModel model; 
            model =(DefaultTableModel) DonorsTable.getModel();
            model.setRowCount(0);
            Statement stmt=Connector.conn.createStatement();
            String sql="select * from donor;";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                String donorid=rs.getString("DonorId");
                String name=rs.getString("DonorName");
                String sex=rs.getString("Sex");
                String dob=rs.getString("DOB");
                String age=rs.getString("Age");
                String emailid=rs.getString("EmailId");
                String phoneno=rs.getString("PhoneNo");
                String address=rs.getString("Address");
                String bloodtype=rs.getString("BloodType");
                model.addRow(new Object[] {donorid,name,sex,dob,age,emailid,phoneno,address,bloodtype});
            }
            rs.close();
            stmt.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_ViewDonorsActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Connector con=new Connector();
        con.createConnection();
        try
        {
            if(IdText.getText().equals("") || UpdateText.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Invalid Information");
            }
            else
            {
                String updatefield=UpdateCombo.getSelectedItem().toString();
                Statement stmt=conn.createStatement();
                PreparedStatement pst;
                String sql="update donor set "+updatefield+"=? where DonorId=?;";
                pst=conn.prepareStatement(sql);
                pst.setString(1,UpdateText.getText());
                pst.setString(2,IdText.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Updated successfully");
                IdText.setText("");
                 UpdateText.setText("");
            }
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Update Unsuccessful");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
       Connector con=new Connector();
       con.createConnection();
       try
       {
           if(DeleteDonorText.getText().equals(""))
           {
               JOptionPane.showMessageDialog(null,"Invalid Information");
           }
           else
           {
         Statement stmt=conn.createStatement();
         PreparedStatement p;
         String sql="delete from donor where DonorId=?;";
         p=conn.prepareStatement(sql);
         p.setString(1,DeleteDonorText.getText());
         p.execute();
         
         DefaultTableModel model; 
            model =(DefaultTableModel) DeleteTable.getModel();
            model.setRowCount(0);
            String sql1="select DonorId,DonorName,BloodType,PhoneNo from donor;";
            ResultSet rs=stmt.executeQuery(sql1);
            while(rs.next())
            {
                String id= rs.getString("DonorId");
                String name=rs.getString("DonorName");
                String bloodtype=rs.getString("BloodType");
                String phoneno=rs.getString("PhoneNo");
                model.addRow(new Object[] {id,name,bloodtype,phoneno});
            }
            JOptionPane.showMessageDialog(null,"Deletion successful");
       }
       }
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Deletion unsucessful");
        }
       
       
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connector con=new Connector();
        con.createConnection();
        try
        {
            
            DefaultTableModel model; 
            model =(DefaultTableModel) DonorsTable.getModel();
            model.setRowCount(0);
            Statement smt=conn.createStatement();
            PreparedStatement p;
            String sql="call GETDONORDETAILS(?);";
            p=conn.prepareCall(sql);
            p.setString(1,Blood1.getSelectedItem().toString());
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
            String donorid=rs.getString("DonorId");
                String name=rs.getString("DonorName");
                String sex=rs.getString("Sex");
                String dob=rs.getString("DOB");
                String age=rs.getString("Age");
                String emailid=rs.getString("EmailId");
                String phoneno=rs.getString("PhoneNo");
                String address=rs.getString("Address");
                String bloodtype=rs.getString("BloodType");
                model.addRow(new Object[] {donorid,name,sex,dob,age,emailid,phoneno,address,bloodtype});
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void DonorRegistration()
        
   
{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton AgeButton;
    private javax.swing.JComboBox<String> Blood;
    private javax.swing.JComboBox<String> Blood1;
    private javax.swing.JLabel BloodType;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField DD;
    private javax.swing.JTextField DOB;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField DeleteDonorText;
    private javax.swing.JTable DeleteTable;
    private javax.swing.JTextArea DonorAddress;
    private javax.swing.JTextField DonorAge;
    private javax.swing.JTextField DonorEmailId;
    private javax.swing.JButton DonorIdButton;
    private javax.swing.JTextField DonorIdText;
    private javax.swing.JTextField DonorName;
    private javax.swing.JTextField DonorPhoneNumber;
    private javax.swing.JComboBox<String> DonorSex;
    private javax.swing.JTable DonorsTable;
    private javax.swing.JLabel EmailId;
    private javax.swing.JTextField IdText;
    private javax.swing.JTextField MM;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel Sex;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> UpdateCombo;
    private javax.swing.JTextField UpdateText;
    private javax.swing.JButton ViewDonors;
    private javax.swing.JTextField YYYY;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
