/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import static bloodbank.Connector.conn;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
        showDate();
    }
    public void showDate()
    {
        Date d=new Date();
        SimpleDateFormat sf=new SimpleDateFormat("yyyy/MM/dd");
        DateText.setText(sf.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Order = new javax.swing.JLabel();
        BloodType = new javax.swing.JLabel();
        Blood = new javax.swing.JComboBox<>();
        Quantity = new javax.swing.JLabel();
        QuantityText = new javax.swing.JTextField();
        HospitaId = new javax.swing.JLabel();
        HospitalIdText = new javax.swing.JTextField();
        HospitaId1 = new javax.swing.JLabel();
        DateText = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        OrderIdButton = new javax.swing.JButton();
        OrderIdText = new javax.swing.JTextField();
        CostButton = new javax.swing.JButton();
        CostText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        Order.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Order.setForeground(new java.awt.Color(153, 0, 153));
        Order.setText("ORDER");

        BloodType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BloodType.setText("BloodType");

        Blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        Quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quantity.setText("Quantity");

        HospitaId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HospitaId.setText("Hospital Id");

        HospitaId1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HospitaId1.setText("Date");

        DateText.setEditable(false);

        ClearButton.setBackground(new java.awt.Color(0, 153, 153));
        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(153, 0, 153));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        CloseButton.setBackground(new java.awt.Color(0, 153, 153));
        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(153, 0, 153));
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(0, 153, 153));
        SubmitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(153, 0, 153));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        OrderIdButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OrderIdButton.setText("Order ID");
        OrderIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderIdButtonActionPerformed(evt);
            }
        });

        OrderIdText.setEditable(false);

        CostButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CostButton.setText("Cost");
        CostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostButtonActionPerformed(evt);
            }
        });

        CostText.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ClearButton)
                        .addGap(29, 29, 29)
                        .addComponent(CloseButton)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BloodType)
                            .addComponent(Quantity)
                            .addComponent(HospitaId)
                            .addComponent(OrderIdButton)
                            .addComponent(HospitaId1)
                            .addComponent(CostButton))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DateText, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuantityText)
                            .addComponent(HospitalIdText)
                            .addComponent(OrderIdText)
                            .addComponent(CostText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Order)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Order)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderIdButton)
                    .addComponent(OrderIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodType)
                    .addComponent(Blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostButton)
                    .addComponent(CostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospitaId)
                    .addComponent(HospitalIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospitaId1)
                    .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(CloseButton)
                    .addComponent(SubmitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Blood Type", "Quantity", "Cost", "Hospital ID", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrdersTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        OrderIdText.setText("");
        QuantityText.setText("");
        HospitalIdText.setText("");
        CostText.setText("");
        DateText.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.dispose();
        Welcome w=new Welcome();
        w.Welcome();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
         Connector con=new Connector();
        con.createConnection();
       
        try {
            
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst;
            String sql="Insert into orders(OrderId,BloodType,Quantity,Cost,HospitalId,Date) values(?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,OrderIdText.getText());
             pst.setString(2,Blood.getSelectedItem().toString());
              pst.setString(3,QuantityText.getText()); 
               pst.setString(4,CostText.getText());
               pst.setString(5,HospitalIdText.getText());
                pst.setString(6,DateText.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Order accepted");
            
            
            
            DefaultTableModel model=(DefaultTableModel) OrdersTable.getModel();
            Statement stmt1=Connector.conn.createStatement();
            String s="select * from orders where OrderId=(select max(OrderId) from orders);";
            ResultSet rs1=stmt1.executeQuery(s);
            while(rs1.next())
            {
                String orderid=rs1.getString("OrderId");
                String bloodtype=rs1.getString("BloodType");
                int quantity=rs1.getInt("Quantity");
                int cost=rs1.getInt("Cost");
                String hospitalid=rs1.getString("HospitalId");
                String date=rs1.getString("Date");
                model.addRow(new Object[] {orderid,bloodtype,quantity,cost,hospitalid,date});
            }
            rs1.close();
            stmt1.close();
            
        }
            
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void OrderIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderIdButtonActionPerformed
      try{   
        Connector con=new Connector();
        con.createConnection();
        Statement stmt=Connector.conn.createStatement();
        String sql="select OrderId+1 from orders where OrderId=(select max(OrderId) from orders);";
        ResultSet rs=stmt.executeQuery(sql);
        while(rs.next())
        {
        OrderIdText.setText(rs.getString("OrderId+1"));      
        }
    } 
    catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }              
    }//GEN-LAST:event_OrderIdButtonActionPerformed

    private void CostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostButtonActionPerformed

       try
        {
        
        Connector con=new Connector();
        con.createConnection();
        PreparedStatement ps;
        ps = Connector.conn.prepareStatement("SELECT cost from blood where bloodtype=?;");
            ps.setString(1, Blood.getSelectedItem().toString());
            ResultSet result = ps.executeQuery();
            while(result.next())
            {
                String q= QuantityText.getText();
                int quan=Integer.parseInt(q);
                String c=result.getString("cost");
                int cos=Integer.parseInt(c);
                int r=cos*quan;
                String res=String.valueOf(r);
                
                CostText.setText(res);
            }

          
        }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
       
       
       
    }//GEN-LAST:event_CostButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Orders() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Blood;
    private javax.swing.JLabel BloodType;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton CostButton;
    private javax.swing.JTextField CostText;
    private javax.swing.JTextField DateText;
    private javax.swing.JLabel HospitaId;
    private javax.swing.JLabel HospitaId1;
    private javax.swing.JTextField HospitalIdText;
    private javax.swing.JLabel Order;
    private javax.swing.JButton OrderIdButton;
    private javax.swing.JTextField OrderIdText;
    private javax.swing.JTable OrdersTable;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField QuantityText;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
